# Environment variables
# - HOST_NAME
# - USER_NAME
# - PORT_NUM
# - USER_PASS
# - APP_DIR
# - UWSGI_LOG
# - UWSGI_PID
 
version: 2
jobs:u
  deploy:
    docker:
      - image: sickp/alpine-sshd
 
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "1a:87:f5:b4:33:1d:65:a9:0f:06:f1:88:28:78:69:69"
 
      # - run:
      #     name: Start ssh-keyscan
      #     command: |
      #       ssh-keyscan -p ${PORT_NUM} ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - run:
          name: Start release deploy
          command: ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -p ${PORT_NUM} "cd ${APP_DIR}; echo ${USER_PASS} | sudo -S git pull; echo ${USER_PASS} | sudo yarn install; echo ${USER_PASS} | sudo yarn build; echo ${USER_PASS} | sudo -S forever list; echo ${USER_PASS} | sudo -S pgrep -f nuxt | sudo xargs kill -9; echo ${USER_PASS} | sudo -S forever start -c "yarn start" ./"

workflows:
  version: 2
  deploy_to_server: 
    jobs: 
      - deploy:
          filters:
            branches:
              only: release