# Environment variables
# - HOST_NAME
# - USER_NAME
# - PORT_NUM
# - USER_PASS
# - APP_DIR
# - UWSGI_LOG
# - UWSGI_PID
 
version: 2
jobs:
  deploy:
    docker:
      - image: sickp/alpine-sshd
 
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "a4:73:85:e2:8e:ce:69:b6:ff:d4:c3:ee:62:fb:a9:ea"
 
      # - run:
      #     name: Start ssh-keyscan
      #     command: |
      #       ssh-keyscan -p ${PORT_NUM} ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - run:
          name: Start release deploy
          command: ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -p ${PORT_NUM} "cd ${APP_DIR}; echo ${USER_PASS} | sudo -S git pull; sudo yarn install; sudo yarn build; sudo forever list; sudo pgrep -f nuxt | sudo xargs kill -9; sudo forever start -c "yarn start" ./"

workflows:
  version: 2
  deploy_to_server: 
    jobs: 
      - deploy:
          filters:
            branches:
              only: release