query($page_size: Int, $endCursor: String!){
  allProjects(first:$page_size, after: $endCursor){
    edges{
      node{
        id
        header
        name
        user{
          username
          logo
          position
        }
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}