query ($id: ID!){
  project(id: $id){
    id
    name
    content
    header
    startAt
    place
    contact
    user {
      id
      username
    }
    tags{
      edges{
        node{
          id
          name
          logo
        }
      }
    }
  }
  allTags{
    edges{
      node{
        id
        name
      }
    }
  }
}
