query($token: String!){
  hostProjects(token:$token) {
    edges{
      node{
        id
        thumbnail
        header
        name
        isOpen
        isPublic
        user{
          id
          username
          logo
        }
      }
    }
  }
}
