query ($id: ID!){
  project(id: $id){
    name
    content
    header
    user {
      id
      username
      logo
    }
    tags{
      edges{
        node{
          id
          name
        }
      }
    }
  }
}